blue/urls.py
from django.urls import path
from . import views 


app_name='blue'

urlpatterns = [
    path('', views.app,name='app'),
    path('contact', views.contact,name='contact'),
    path('list', views.list,name='list'),
     path('product/<int:product_id>/details', views.details, name='product_detail'),
    path('success', views.success,name='success'),

    path('category/<int:category_id>/', views.category, name='category'),
]

dicussion_board/dicussion_board/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dicussion_board/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blue.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blue/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self):
        return self.name
    

class categoriesPRODUCT(models.Model):
    namecategorie = models.CharField(max_length=100)

    def __str__(self):
        return self.namecategorie
class profile(models.Model):
    image1 = models.ImageField(upload_to='product_images/')


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    categories1 = models.ForeignKey(categoriesPRODUCT, on_delete=models.CASCADE)
    image1 = models.ImageField(upload_to='product_images/')
    image2 = models.ImageField(upload_to='product_images/')
    image3 = models.ImageField(upload_to='product_images/',blank=True)
    image4 = models.ImageField(upload_to='product_images/',blank=True)
    image5 = models.ImageField(upload_to='product_images/',blank=True)
    details = models.TextField()

    def __str__(self):
        return self.name
    
from django.db import models

class AboutUs(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='about_us_images/')

    def __str__(self):
        return self.title

blue/views.py
from django.shortcuts import render
from .models import Contact

from .models import AboutUs,profile

# def app(request):
#     about_us = AboutUs.objects.first()  # استرداد أول كائن "AboutUs" من قاعدة البيانات
#     return render(request, 'app.html', {'about_us': about_us})
from .models import categoriesPRODUCT

def app(request):
    about_us = AboutUs.objects.first()
    profile_obj = profile.objects.first()
    categories = categoriesPRODUCT.objects.all()  # استرداد جميع كائنات الفئات من قاعدة البيانات
    return render(request, 'app.html', {'about_us': about_us, 'profile': profile_obj, 'categories': categories})
def success(request):
    return render(request , 'success.html')


from django.shortcuts import render
from .models import categoriesPRODUCT, Product

def category(request, category_id):
    category = categoriesPRODUCT.objects.get(id=category_id)
    products = Product.objects.filter(categories1=category)
    categories = categoriesPRODUCT.objects.all()
    # return render(request, 'list.html', {'products': products, 'categories': categories})
    return render(request, 'category.html', {'category': category, 'products': products, 'categories': categories})



def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        Contact.objects.create(name=name, email=email, phone=phone, message=message)
        return render(request, 'success.html')
    return render(request, 'contact.html')

# def list(request):
#     return render(request , 'list.html')

from .models import Product

def list(request):
    products = Product.objects.all()
    categories = categoriesPRODUCT.objects.all()
    return render(request, 'list.html', {'products': products, 'categories': categories})
from django.shortcuts import render, get_object_or_404

from django.shortcuts import render, get_object_or_404
from .models import Product


def details(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    return render(request, 'details.html', {'product': product})





   
from django.shortcuts import render
# from .models import Product

# def details(request, product_id):
#     product = Product.objects.get(pk=product_id)
#     return render(request, 'details.html', {'product': product})

blue/templates/app.html
{%load static%}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Blue Med</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link href="{% static 'assets/img/apple-touch-icon.png" rel="apple-touch-icon' %}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        {% comment %} <h1 class="d-flex align-items-center">Blue Med</h1> {% endcomment %}
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'blue:app' %}">Home</a></li>
          <li><a href="{% url 'blue:list' %}">Product</a></li>
      
          <li><a href="#about">ABOUT US</a></li>
          <li><a href="{% url 'blue:contact' %}">Contact</a></li>
          <li><a ></a></li>
          <li>
            <select onchange="location = this.value;">
              
              <option selected disabled>Categories</option>
              {% for category in categories %}
                <option value="{% url 'blue:category' category.id %}">{{ category.namecategorie }}</option>
              {% endfor %}
            </select>
          </li>
        </ul>
   
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">


  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

      <div class="carousel-inner" role="listbox">

        <!-- Slide 1 -->
        {% comment %} <div class="carousel-item active" style="background-image: url({% static 'assets/img/slide/slide-1.jpg' %})"> {% endcomment %}
          <div class="carousel-item active" style="background-image: url({{ profile.image1.url }})">
          <div class="container">
            <h2>Welcome to <span>Blue Med</span></h2>
            <p>Our beauty tools company prides itself on high level of professionalism and quality in all of our products. <br> we always strive to provide the best products that meet our customer's need and achieve the highest standards of quality and safety.</p>
            <a  href="{% url 'blue:list' %}" class="btn-get-started scrollto"> Browse Products</a>
          </div>
        </div>



      </div>

  

    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Featured Services Section ======= -->
    <section id="featured-services" class="featured-services">
      <div class="container" data-aos="fade-up">
        <div class="row">
          <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
              <div class="icon"><i class="fas fa-heartbeat"></i></div>
              <h4 class="title"><a href="">Your Trusted Source for Medical and Cosmetic Supplies</a></h4>
              <p class="description">We are a leading distributor of high-quality medical and cosmetic supplies, catering to the needs of healthcare professionals and beauty salons.</p>
            </div>
          </div>
    
          <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
              <div class="icon"><i class="fas fa-pills"></i></div>
              <h4 class="title"><a href="">Your Comprehensive Pharmaceutical Solutions</a></h4>
              <p class="description">We offer a wide range of pharmaceutical products.</p>
            </div>
          </div>
    
          <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
              <div class="icon"><i class="fas fa-thermometer"></i></div>
              <h4 class="title"><a href="">Superior Medical Equipment for Precise Diagnoses</a></h4>
              <p class="description">Our extensive inventory includes top-quality medical equipment and instruments, supporting accurate diagnoses and effective treatments.</p>
            </div>
          </div>
    
          <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
            <div class="icon-box" data-aos="fade-up" data-aos-delay="400">
              <div class="icon"><i class="fas fa-dna"></i></div>
              <h4 class="title"><a href="">Trusted Innovation </a></h4>
              <p class="description">We are committed to delivering trusted and innovative products, meeting the diverse needs of our customers in the medical and cosmetic fields.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ======= Cta Section ======= -->
    <section id="cta" class="cta">
      <div class="container" data-aos="zoom-in">

        <div class="text-center">
          <h3> Need help now?</h3>
          <!-- <p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> -->
          <a class="cta-btn scrollto" href="{% url 'blue:contact' %}">Connect with us</a>
        </div>

      </div>
    </section><!-- End Cta Section -->

    <!-- ======= About Us Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>About Us</h2>
          
        </div>

        {% if about_us %}
        <div class="row">
          <div class="col-lg-6" data-aos="fade-right">
            <img src="{{ about_us.image.url }}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content" data-aos="fade-left">
            <h3>{{ about_us.title }}.</h3>
            <p class="fst-italic">
            {{ about_us.description }}
            </p>
            {% else %}
            <p>  No Data "About Us" .</p>
          {% endif %}
          
          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->


    {% comment %} <!-- ======= Features Section ======= -->
    <section id="features" class="features">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-6 order-2 order-lg-1" data-aos="fade-right">
            <div class="icon-box mt-5 mt-lg-0">
              <i class="bx bx-receipt"></i>
              <h4>Est labore ad</h4>
              <p>Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip</p>
            </div>
            <div class="icon-box mt-5">
              <i class="bx bx-cube-alt"></i>
              <h4>Harum esse qui</h4>
              <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt</p>
            </div>
            <div class="icon-box mt-5">
              <i class="bx bx-images"></i>
              <h4>Aut occaecati</h4>
              <p>Aut suscipit aut cum nemo deleniti aut omnis. Doloribus ut maiores omnis facere</p>
            </div>
            <div class="icon-box mt-5">
              <i class="bx bx-shield"></i>
              <h4>Beatae veritatis</h4>
              <p>Expedita veritatis consequuntur nihil tempore laudantium vitae denat pacta</p>
            </div>
          </div>
          <div class="image col-lg-6 order-1 order-lg-2" style='background-image: url("{% static 'assets/img/features.jpg' %}");' data-aos="zoom-in"></div>
        </div>

      </div> {% endcomment %}
    </section><!-- End Features Section -->
<!-- ======= Services Section ======= -->
<section id="services" class="services services">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>Services</h2>
      <p>We offer a wide range of trusted and innovative medical and cosmetic pharmaceutical products to meet diverse customer needs.</p>
    </div>

    <div class="row">
      <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="100">
        <div class="icon"><i class="fas fa-heartbeat"></i></div>
        <h4 class="title"><a href="">Your Trusted Source </a></h4>
        <p class="description">We provide high-quality medical pharmaceuticals.</p>
      </div>
      <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="200">
        <div class="icon"><i class="fas fa-pills"></i></div>
        <h4 class="title"><a href="">Skin & Beauty</a></h4>
        <p class="description">Our extensive range of cosmetic pharmaceuticals offers innovative solutions for beauty salons and individuals seeking effective skincare and aesthetic treatments.</p>
      </div>
      <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="300">
        <div class="icon"><i class="fas fa-hospital-user"></i></div>
        <h4 class="title"><a href="">Reliable Medical and Cosmetic Pharmaceuticals </a></h4>
        <p class="description">We are committed to delivering trusted medical and cosmetic pharmaceutical products, providing reliable options for healthcare professionals and beauty experts.</p>
      </div>
    </div>

  </div>
</section>
<!-- End Services Section -->
  



  

  </main><!-- End #main -->


  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

blue/templates/category.html
{%load static%}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Blue Med</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link href="{% static 'assets/img/apple-touch-icon.png" rel="apple-touch-icon' %}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <style>
    body{
      background-color:#aaaa;
  </style>
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
    
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a  href="{% url 'blue:app' %}" >Home</a></li>
          <li><a href="{% url 'blue:list' %}" >Product</a></li>
          {% comment %} <li><a href="services.html" class="active">Services</a></li> {% endcomment %}
          <li><a  href="{% url 'blue:app' %}" >ABOUT US</a></li>
          <li><a  href="{% url 'blue:contact' %}" >Contact</a></li>
            
           
          <li><a ></a></li>
          
          <li>
            <select onchange="location = this.value;" >
              
              <option selected disabled>Categories</option>
              {% for category in categories %}
                <option value="{% url 'blue:category' category.id %}" >{{ category.namecategorie }}</option>
              {% endfor %}
            </select>
          </li>
        </ul>

      </nav>

    </div>
  </header>

  <main id="main">

<style>.card img {
  display: inline-block; /* أو display: inline-block; */
}</style>
<br><br><br><br>
<section id="about-boxes" class="about-boxes">
  <div class="container" data-aos="fade-up">
    <div class="row">
        <h1>{{ category.namecategorie }}</h1>   
      {% for product in products %}
      <div class="col-lg-4 col-md-5 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
        <div class="card">
          <div class="image-container">
            <img src="{{ product.image1.url }}" alt="" class="img-fluid">
            
          <div class="card-icon">
            <i class="ri-brush-4-line"></i>
          </div>
          <div class="card-body">
            <h5 class="card-title"><a href="/product/{{ product.id }}/details">{{ product.name }}</a></h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="/product/{{ product.id }}/details">View</a>
          </div>
        </div>
      </div></div>
      {% endfor %}
    </div>
  </div>
</section>






    </div>
  </div>
</section><!-- End Services Cards Section --> 
    </div>
  </div>
</section><!-- End Services Cards Section -->

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  {% comment %} <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script> {% endcomment %}

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

blue/templates/list.html
{%load static%}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Blue Med</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link href="{% static 'assets/img/apple-touch-icon.png" rel="apple-touch-icon' %}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>




<style>.card img {
  display: inline-block; /* أو display: inline-block; */
}</style>

{% comment %}  {% endcomment %}


{% comment %}  {% endcomment %}
<body>
  <style>
    body{
      background-color:#aaaa;
  </style>

  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
       
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a  href="{% url 'blue:app' %}" >Home</a></li>
          <li><a href="{% url 'blue:list' %}" >Product</a></li>
          {% comment %} <li><a href="services.html" class="active">Services</a></li> {% endcomment %}
          <li><a  href="{% url 'blue:app' %}">ABOUT US</a></li>
          <li><a  href="{% url 'blue:contact' %}">Contact</a></li>
          <li><a ></a></li>
          
          <li  class="active">
            <select onchange="location = this.value;">
              
              <option selected disabled>Categories</option>
              {% for category in categories %}
                <option value="{% url 'blue:category' category.id %}" >{{ category.namecategorie }}</option>
              {% endfor %}
            </select>
          </li>
        </ul>
   
      </nav>
    </div>
  </header>

  <main id="main">




<br><br><br><br>
<section id="about-boxes" class="about-boxes">
  <div class="container" data-aos="fade-up">
    <div class="row">
      {% for product in products %}
      <div class="col-lg-4 col-md-5 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
        <div class="card">

          <div class="image-container">
            <img src="{{ product.image1.url }}" alt="" class="img-fluid">
            
          {% comment %} {% if product.image1.url  %}
          <a href="/product/{{ product.id }}/details">
            <img src="{{ product.product_image.url }}" alt=" " style="border: 1px solid #000000;">
          </a>
          {% else %}
          <a href="{% static 'assets/img/features.jpg' %}" data-gallery="portfolioGallery" class="portfolio-lightbox preview-link" title="Card 1"><i class="bx bx-plus"></i></a>
          {% endif %} {% endcomment %}
          <div class="card-icon">
            <i class="ri-brush-4-line"></i>
          </div>
          <div class="card-body">
            <h5 class="card-title"><a href="/product/{{ product.id }}/details">{{ product.name }}</a></h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="/product/{{ product.id }}/details">View</a>
          </div>
        </div>
      </div></div>
      {% endfor %}
    </div>
  </div>
</section>






{% comment %} 










<section id="services-cards" class="services-cards">
  <div class="container" data-aos="fade-up">
    <div class="row gy-4">
      {% for product in products %}
      <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
        <div class="card-item">
          <div class="row">
            <div class="col-xl-5">
              <a href="/product/{{ product.id }}/details">
                <img src="{{ product.image1.url }}" alt=" " style="border: 1px solid #000000;">
              </a>
            </div>
            <div class="col-xl-7 d-flex align-items-center">
              <div class="card-body">
                <h4 class="card-title"><h1>{{ product.name }}</h1></h4>
                <p>{{ product.description }}</p>
                <a href="/product/{{ product.id }}/details">Details </a>
              </div>
            </div>
          </div>
        </div>
      </div><!-- <div class="col-xl-5">
        <a href="/product/{{ product.id }}/details">
          <img src="{{ product.image1.url }}" alt=" " style="border: 1px solid #000000;">
        </a>
      </div>
      <div class="col-xl-7 d-flex align-items-center">
        <div class="card-body">
          <h4 class="card-title"><h1>{{ product.name }}</h1></h4>
          <p>{{ product.description }}</p>
          <a href="/product/{{ product.id }}/details">Details </a>
        </div>
      </div> -->
      {% endfor %} {% endcomment %}
    </div>
  </div>
</section><!-- End Services Cards Section --> 
    </div>
  </div>
</section><!-- End Services Cards Section -->

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  {% comment %} <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script> {% endcomment %}

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>